# File generated by CompCert Release: 20.04i, Build: 7465380, Tag: auto/2020/08/30/1918, Branch: master
# Command line: -target rv32-linux -u _start -u _cstart -s crt0.c -o crt0.s -I /local/hdd/meyer/picolib/out/riscv32/picolibc/include -fall -c -S
	.option nopic
	.text
	.balign 2
	.globl _cstart
_cstart:
	mv	x30, x2
	addi	x2, x2, -16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
# begin inline assembly
	.option push
.option norelax
la gp, __global_pointer$
.option pop
# end inline assembly
# begin inline assembly
	csrr x5, mstatus
# end inline assembly
	lui	x31, 2
	or	x6, x5, x31
# begin inline assembly
	csrw mstatus, x6
# end inline assembly
# begin inline assembly
	csrwi fcsr, 0
# end inline assembly
	lui	x10, %hi(__data_start)
	addi	x10, x10, %lo(__data_start)
	lui	x11, %hi(__data_source)
	addi	x11, x11, %lo(__data_source)
	lui	x12, %hi(__data_size)
	addi	x12, x12, %lo(__data_size)
	call	memcpy
	lui	x10, %hi(__bss_start)
	addi	x10, x10, %lo(__bss_start)
	addi	x11, x0, 0
	lui	x12, %hi(__bss_size)
	addi	x12, x12, %lo(__bss_size)
	call	memset
	addi	x10, x0, 0
	addi	x11, x0, 0
	call	main
	lw	x1, 4(x2)
	addi	x2, x2, 16
	j	_exit
	.type	_cstart, @function
	.size	_cstart, . - _cstart
	.section	".text.init.enter","ax",%progbits
	.balign 2
	.globl _start
_start:
# begin inline assembly
	.option push
.option norelax
la sp, __stack
.option pop
# end inline assembly
# begin inline assembly
	j _cstart
# end inline assembly
	.type	_start, @function
	.size	_start, . - _start
